package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.domain.Guest;
import net.suncaper.demo.domain.GuestExample;
import org.apache.ibatis.annotations.Param;

public interface GuestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    long countByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    int deleteByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    int deleteByPrimaryKey(Integer gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    int insert(Guest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    int insertSelective(Guest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    List<Guest> selectByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    Guest selectByPrimaryKey(Integer gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Guest record, @Param("example") GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    int updateByExample(@Param("record") Guest record, @Param("example") GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    int updateByPrimaryKeySelective(Guest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbg.generated Wed Jun 26 20:17:15 CST 2019
     */
    int updateByPrimaryKey(Guest record);
}