package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.domain.Hotel;
import net.suncaper.demo.domain.HotelExample;
import org.apache.ibatis.annotations.Param;

public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    long countByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int deleteByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int deleteByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    List<Hotel> selectByExampleWithBLOBs(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    List<Hotel> selectByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    Hotel selectByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int updateByExample(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int updateByPrimaryKeySelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int updateByPrimaryKey(Hotel record);
}