package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.domain.R_img;
import net.suncaper.demo.domain.R_imgExample;
import org.apache.ibatis.annotations.Param;

public interface R_imgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    long countByExample(R_imgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int deleteByExample(R_imgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int deleteByPrimaryKey(Integer roomImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int insert(R_img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int insertSelective(R_img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    List<R_img> selectByExample(R_imgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    R_img selectByPrimaryKey(Integer roomImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") R_img record, @Param("example") R_imgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int updateByExample(@Param("record") R_img record, @Param("example") R_imgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int updateByPrimaryKeySelective(R_img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    int updateByPrimaryKey(R_img record);
}