server:
  port: 8280
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml


spring:
  datasource:
     url: jdbc:mysql://localhost:3306/hos?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
     username: root
     password: admin
     driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false


logging:
  level:
    org.thymeleaf: debug