package net.suncaper.demo.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HotelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public HotelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andHotelIdIsNull() {
            addCriterion("hotel_id is null");
            return (Criteria) this;
        }

        public Criteria andHotelIdIsNotNull() {
            addCriterion("hotel_id is not null");
            return (Criteria) this;
        }

        public Criteria andHotelIdEqualTo(Integer value) {
            addCriterion("hotel_id =", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotEqualTo(Integer value) {
            addCriterion("hotel_id <>", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThan(Integer value) {
            addCriterion("hotel_id >", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hotel_id >=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThan(Integer value) {
            addCriterion("hotel_id <", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThanOrEqualTo(Integer value) {
            addCriterion("hotel_id <=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdIn(List<Integer> values) {
            addCriterion("hotel_id in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotIn(List<Integer> values) {
            addCriterion("hotel_id not in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdBetween(Integer value1, Integer value2) {
            addCriterion("hotel_id between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hotel_id not between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(Integer value) {
            addCriterion("city_id =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(Integer value) {
            addCriterion("city_id <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(Integer value) {
            addCriterion("city_id >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("city_id >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(Integer value) {
            addCriterion("city_id <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(Integer value) {
            addCriterion("city_id <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<Integer> values) {
            addCriterion("city_id in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<Integer> values) {
            addCriterion("city_id not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(Integer value1, Integer value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNull() {
            addCriterion("hotel_name is null");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNotNull() {
            addCriterion("hotel_name is not null");
            return (Criteria) this;
        }

        public Criteria andHotelNameEqualTo(String value) {
            addCriterion("hotel_name =", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotEqualTo(String value) {
            addCriterion("hotel_name <>", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThan(String value) {
            addCriterion("hotel_name >", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_name >=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThan(String value) {
            addCriterion("hotel_name <", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThanOrEqualTo(String value) {
            addCriterion("hotel_name <=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLike(String value) {
            addCriterion("hotel_name like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotLike(String value) {
            addCriterion("hotel_name not like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameIn(List<String> values) {
            addCriterion("hotel_name in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotIn(List<String> values) {
            addCriterion("hotel_name not in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameBetween(String value1, String value2) {
            addCriterion("hotel_name between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotBetween(String value1, String value2) {
            addCriterion("hotel_name not between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andAddresslineIsNull() {
            addCriterion("addressline is null");
            return (Criteria) this;
        }

        public Criteria andAddresslineIsNotNull() {
            addCriterion("addressline is not null");
            return (Criteria) this;
        }

        public Criteria andAddresslineEqualTo(String value) {
            addCriterion("addressline =", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineNotEqualTo(String value) {
            addCriterion("addressline <>", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineGreaterThan(String value) {
            addCriterion("addressline >", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineGreaterThanOrEqualTo(String value) {
            addCriterion("addressline >=", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineLessThan(String value) {
            addCriterion("addressline <", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineLessThanOrEqualTo(String value) {
            addCriterion("addressline <=", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineLike(String value) {
            addCriterion("addressline like", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineNotLike(String value) {
            addCriterion("addressline not like", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineIn(List<String> values) {
            addCriterion("addressline in", values, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineNotIn(List<String> values) {
            addCriterion("addressline not in", values, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineBetween(String value1, String value2) {
            addCriterion("addressline between", value1, value2, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineNotBetween(String value1, String value2) {
            addCriterion("addressline not between", value1, value2, "addressline");
            return (Criteria) this;
        }

        public Criteria andPhoto1IsNull() {
            addCriterion("photo1 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto1IsNotNull() {
            addCriterion("photo1 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto1EqualTo(String value) {
            addCriterion("photo1 =", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotEqualTo(String value) {
            addCriterion("photo1 <>", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1GreaterThan(String value) {
            addCriterion("photo1 >", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1GreaterThanOrEqualTo(String value) {
            addCriterion("photo1 >=", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1LessThan(String value) {
            addCriterion("photo1 <", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1LessThanOrEqualTo(String value) {
            addCriterion("photo1 <=", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1Like(String value) {
            addCriterion("photo1 like", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotLike(String value) {
            addCriterion("photo1 not like", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1In(List<String> values) {
            addCriterion("photo1 in", values, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotIn(List<String> values) {
            addCriterion("photo1 not in", values, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1Between(String value1, String value2) {
            addCriterion("photo1 between", value1, value2, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotBetween(String value1, String value2) {
            addCriterion("photo1 not between", value1, value2, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto2IsNull() {
            addCriterion("photo2 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto2IsNotNull() {
            addCriterion("photo2 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto2EqualTo(String value) {
            addCriterion("photo2 =", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotEqualTo(String value) {
            addCriterion("photo2 <>", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2GreaterThan(String value) {
            addCriterion("photo2 >", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2GreaterThanOrEqualTo(String value) {
            addCriterion("photo2 >=", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2LessThan(String value) {
            addCriterion("photo2 <", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2LessThanOrEqualTo(String value) {
            addCriterion("photo2 <=", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2Like(String value) {
            addCriterion("photo2 like", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotLike(String value) {
            addCriterion("photo2 not like", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2In(List<String> values) {
            addCriterion("photo2 in", values, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotIn(List<String> values) {
            addCriterion("photo2 not in", values, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2Between(String value1, String value2) {
            addCriterion("photo2 between", value1, value2, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotBetween(String value1, String value2) {
            addCriterion("photo2 not between", value1, value2, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto3IsNull() {
            addCriterion("photo3 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto3IsNotNull() {
            addCriterion("photo3 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto3EqualTo(String value) {
            addCriterion("photo3 =", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotEqualTo(String value) {
            addCriterion("photo3 <>", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3GreaterThan(String value) {
            addCriterion("photo3 >", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3GreaterThanOrEqualTo(String value) {
            addCriterion("photo3 >=", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3LessThan(String value) {
            addCriterion("photo3 <", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3LessThanOrEqualTo(String value) {
            addCriterion("photo3 <=", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3Like(String value) {
            addCriterion("photo3 like", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotLike(String value) {
            addCriterion("photo3 not like", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3In(List<String> values) {
            addCriterion("photo3 in", values, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotIn(List<String> values) {
            addCriterion("photo3 not in", values, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3Between(String value1, String value2) {
            addCriterion("photo3 between", value1, value2, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotBetween(String value1, String value2) {
            addCriterion("photo3 not between", value1, value2, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto4IsNull() {
            addCriterion("photo4 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto4IsNotNull() {
            addCriterion("photo4 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto4EqualTo(String value) {
            addCriterion("photo4 =", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4NotEqualTo(String value) {
            addCriterion("photo4 <>", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4GreaterThan(String value) {
            addCriterion("photo4 >", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4GreaterThanOrEqualTo(String value) {
            addCriterion("photo4 >=", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4LessThan(String value) {
            addCriterion("photo4 <", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4LessThanOrEqualTo(String value) {
            addCriterion("photo4 <=", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4Like(String value) {
            addCriterion("photo4 like", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4NotLike(String value) {
            addCriterion("photo4 not like", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4In(List<String> values) {
            addCriterion("photo4 in", values, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4NotIn(List<String> values) {
            addCriterion("photo4 not in", values, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4Between(String value1, String value2) {
            addCriterion("photo4 between", value1, value2, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4NotBetween(String value1, String value2) {
            addCriterion("photo4 not between", value1, value2, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto5IsNull() {
            addCriterion("photo5 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto5IsNotNull() {
            addCriterion("photo5 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto5EqualTo(String value) {
            addCriterion("photo5 =", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5NotEqualTo(String value) {
            addCriterion("photo5 <>", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5GreaterThan(String value) {
            addCriterion("photo5 >", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5GreaterThanOrEqualTo(String value) {
            addCriterion("photo5 >=", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5LessThan(String value) {
            addCriterion("photo5 <", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5LessThanOrEqualTo(String value) {
            addCriterion("photo5 <=", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5Like(String value) {
            addCriterion("photo5 like", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5NotLike(String value) {
            addCriterion("photo5 not like", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5In(List<String> values) {
            addCriterion("photo5 in", values, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5NotIn(List<String> values) {
            addCriterion("photo5 not in", values, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5Between(String value1, String value2) {
            addCriterion("photo5 between", value1, value2, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5NotBetween(String value1, String value2) {
            addCriterion("photo5 not between", value1, value2, "photo5");
            return (Criteria) this;
        }

        public Criteria andStarRatingIsNull() {
            addCriterion("star_rating is null");
            return (Criteria) this;
        }

        public Criteria andStarRatingIsNotNull() {
            addCriterion("star_rating is not null");
            return (Criteria) this;
        }

        public Criteria andStarRatingEqualTo(BigDecimal value) {
            addCriterion("star_rating =", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingNotEqualTo(BigDecimal value) {
            addCriterion("star_rating <>", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingGreaterThan(BigDecimal value) {
            addCriterion("star_rating >", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("star_rating >=", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingLessThan(BigDecimal value) {
            addCriterion("star_rating <", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingLessThanOrEqualTo(BigDecimal value) {
            addCriterion("star_rating <=", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingIn(List<BigDecimal> values) {
            addCriterion("star_rating in", values, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingNotIn(List<BigDecimal> values) {
            addCriterion("star_rating not in", values, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("star_rating between", value1, value2, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("star_rating not between", value1, value2, "starRating");
            return (Criteria) this;
        }

        public Criteria andCheckinIsNull() {
            addCriterion("checkin is null");
            return (Criteria) this;
        }

        public Criteria andCheckinIsNotNull() {
            addCriterion("checkin is not null");
            return (Criteria) this;
        }

        public Criteria andCheckinEqualTo(Date value) {
            addCriterionForJDBCTime("checkin =", value, "checkin");
            return (Criteria) this;
        }

        public Criteria andCheckinNotEqualTo(Date value) {
            addCriterionForJDBCTime("checkin <>", value, "checkin");
            return (Criteria) this;
        }

        public Criteria andCheckinGreaterThan(Date value) {
            addCriterionForJDBCTime("checkin >", value, "checkin");
            return (Criteria) this;
        }

        public Criteria andCheckinGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("checkin >=", value, "checkin");
            return (Criteria) this;
        }

        public Criteria andCheckinLessThan(Date value) {
            addCriterionForJDBCTime("checkin <", value, "checkin");
            return (Criteria) this;
        }

        public Criteria andCheckinLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("checkin <=", value, "checkin");
            return (Criteria) this;
        }

        public Criteria andCheckinIn(List<Date> values) {
            addCriterionForJDBCTime("checkin in", values, "checkin");
            return (Criteria) this;
        }

        public Criteria andCheckinNotIn(List<Date> values) {
            addCriterionForJDBCTime("checkin not in", values, "checkin");
            return (Criteria) this;
        }

        public Criteria andCheckinBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("checkin between", value1, value2, "checkin");
            return (Criteria) this;
        }

        public Criteria andCheckinNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("checkin not between", value1, value2, "checkin");
            return (Criteria) this;
        }

        public Criteria andCheckoutIsNull() {
            addCriterion("checkout is null");
            return (Criteria) this;
        }

        public Criteria andCheckoutIsNotNull() {
            addCriterion("checkout is not null");
            return (Criteria) this;
        }

        public Criteria andCheckoutEqualTo(Date value) {
            addCriterionForJDBCTime("checkout =", value, "checkout");
            return (Criteria) this;
        }

        public Criteria andCheckoutNotEqualTo(Date value) {
            addCriterionForJDBCTime("checkout <>", value, "checkout");
            return (Criteria) this;
        }

        public Criteria andCheckoutGreaterThan(Date value) {
            addCriterionForJDBCTime("checkout >", value, "checkout");
            return (Criteria) this;
        }

        public Criteria andCheckoutGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("checkout >=", value, "checkout");
            return (Criteria) this;
        }

        public Criteria andCheckoutLessThan(Date value) {
            addCriterionForJDBCTime("checkout <", value, "checkout");
            return (Criteria) this;
        }

        public Criteria andCheckoutLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("checkout <=", value, "checkout");
            return (Criteria) this;
        }

        public Criteria andCheckoutIn(List<Date> values) {
            addCriterionForJDBCTime("checkout in", values, "checkout");
            return (Criteria) this;
        }

        public Criteria andCheckoutNotIn(List<Date> values) {
            addCriterionForJDBCTime("checkout not in", values, "checkout");
            return (Criteria) this;
        }

        public Criteria andCheckoutBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("checkout between", value1, value2, "checkout");
            return (Criteria) this;
        }

        public Criteria andCheckoutNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("checkout not between", value1, value2, "checkout");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andRatesFromIsNull() {
            addCriterion("rates_from is null");
            return (Criteria) this;
        }

        public Criteria andRatesFromIsNotNull() {
            addCriterion("rates_from is not null");
            return (Criteria) this;
        }

        public Criteria andRatesFromEqualTo(Integer value) {
            addCriterion("rates_from =", value, "ratesFrom");
            return (Criteria) this;
        }

        public Criteria andRatesFromNotEqualTo(Integer value) {
            addCriterion("rates_from <>", value, "ratesFrom");
            return (Criteria) this;
        }

        public Criteria andRatesFromGreaterThan(Integer value) {
            addCriterion("rates_from >", value, "ratesFrom");
            return (Criteria) this;
        }

        public Criteria andRatesFromGreaterThanOrEqualTo(Integer value) {
            addCriterion("rates_from >=", value, "ratesFrom");
            return (Criteria) this;
        }

        public Criteria andRatesFromLessThan(Integer value) {
            addCriterion("rates_from <", value, "ratesFrom");
            return (Criteria) this;
        }

        public Criteria andRatesFromLessThanOrEqualTo(Integer value) {
            addCriterion("rates_from <=", value, "ratesFrom");
            return (Criteria) this;
        }

        public Criteria andRatesFromIn(List<Integer> values) {
            addCriterion("rates_from in", values, "ratesFrom");
            return (Criteria) this;
        }

        public Criteria andRatesFromNotIn(List<Integer> values) {
            addCriterion("rates_from not in", values, "ratesFrom");
            return (Criteria) this;
        }

        public Criteria andRatesFromBetween(Integer value1, Integer value2) {
            addCriterion("rates_from between", value1, value2, "ratesFrom");
            return (Criteria) this;
        }

        public Criteria andRatesFromNotBetween(Integer value1, Integer value2) {
            addCriterion("rates_from not between", value1, value2, "ratesFrom");
            return (Criteria) this;
        }

        public Criteria andRatingAverageIsNull() {
            addCriterion("rating_average is null");
            return (Criteria) this;
        }

        public Criteria andRatingAverageIsNotNull() {
            addCriterion("rating_average is not null");
            return (Criteria) this;
        }

        public Criteria andRatingAverageEqualTo(BigDecimal value) {
            addCriterion("rating_average =", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageNotEqualTo(BigDecimal value) {
            addCriterion("rating_average <>", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageGreaterThan(BigDecimal value) {
            addCriterion("rating_average >", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rating_average >=", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageLessThan(BigDecimal value) {
            addCriterion("rating_average <", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rating_average <=", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageIn(List<BigDecimal> values) {
            addCriterion("rating_average in", values, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageNotIn(List<BigDecimal> values) {
            addCriterion("rating_average not in", values, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rating_average between", value1, value2, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rating_average not between", value1, value2, "ratingAverage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 05 11:23:49 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated Fri Jul 05 11:23:49 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}