package net.suncaper.demo.domain;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_id
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    private String mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_password
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    private String mPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public Manager(String mId, String mPassword) {
        this.mId = mId;
        this.mPassword = mPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public Manager() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_id
     *
     * @return the value of manager.m_id
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public String getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_id
     *
     * @param mId the value for manager.m_id
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public void setmId(String mId) {
        this.mId = mId == null ? null : mId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_password
     *
     * @return the value of manager.m_password
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public String getmPassword() {
        return mPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_password
     *
     * @param mPassword the value for manager.m_password
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public void setmPassword(String mPassword) {
        this.mPassword = mPassword == null ? null : mPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Manager other = (Manager) that;
        return (this.getmId() == null ? other.getmId() == null : this.getmId().equals(other.getmId()))
            && (this.getmPassword() == null ? other.getmPassword() == null : this.getmPassword().equals(other.getmPassword()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getmId() == null) ? 0 : getmId().hashCode());
        result = prime * result + ((getmPassword() == null) ? 0 : getmPassword().hashCode());
        return result;
    }
}