package net.suncaper.demo.domain;

public class R_img {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_img.room_img_id
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    private Integer roomImgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_img.room_id
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_img.img
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    public R_img(Integer roomImgId, Integer roomId, String img) {
        this.roomImgId = roomImgId;
        this.roomId = roomId;
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    public R_img() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_img.room_img_id
     *
     * @return the value of r_img.room_img_id
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    public Integer getRoomImgId() {
        return roomImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_img.room_img_id
     *
     * @param roomImgId the value for r_img.room_img_id
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    public void setRoomImgId(Integer roomImgId) {
        this.roomImgId = roomImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_img.room_id
     *
     * @return the value of r_img.room_id
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_img.room_id
     *
     * @param roomId the value for r_img.room_id
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_img.img
     *
     * @return the value of r_img.img
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_img.img
     *
     * @param img the value for r_img.img
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        R_img other = (R_img) that;
        return (this.getRoomImgId() == null ? other.getRoomImgId() == null : this.getRoomImgId().equals(other.getRoomImgId()))
            && (this.getRoomId() == null ? other.getRoomId() == null : this.getRoomId().equals(other.getRoomId()))
            && (this.getImg() == null ? other.getImg() == null : this.getImg().equals(other.getImg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_img
     *
     * @mbg.generated Thu Jul 04 09:59:50 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoomImgId() == null) ? 0 : getRoomImgId().hashCode());
        result = prime * result + ((getRoomId() == null) ? 0 : getRoomId().hashCode());
        result = prime * result + ((getImg() == null) ? 0 : getImg().hashCode());
        return result;
    }
}