package net.suncaper.demo.domain;

import java.util.Date;

public class Room_quantityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_quantity.room_id
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_quantity.r_date
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    private Date rDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_quantity
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public Room_quantityKey(Integer roomId, Date rDate) {
        this.roomId = roomId;
        this.rDate = rDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_quantity
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public Room_quantityKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_quantity.room_id
     *
     * @return the value of room_quantity.room_id
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_quantity.room_id
     *
     * @param roomId the value for room_quantity.room_id
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_quantity.r_date
     *
     * @return the value of room_quantity.r_date
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public Date getrDate() {
        return rDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_quantity.r_date
     *
     * @param rDate the value for room_quantity.r_date
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    public void setrDate(Date rDate) {
        this.rDate = rDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_quantity
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Room_quantityKey other = (Room_quantityKey) that;
        return (this.getRoomId() == null ? other.getRoomId() == null : this.getRoomId().equals(other.getRoomId()))
            && (this.getrDate() == null ? other.getrDate() == null : this.getrDate().equals(other.getrDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_quantity
     *
     * @mbg.generated Wed Jun 26 20:07:26 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoomId() == null) ? 0 : getRoomId().hashCode());
        result = prime * result + ((getrDate() == null) ? 0 : getrDate().hashCode());
        return result;
    }
}